CREATE DATABASE QLSV
GO

USE QLSV
GO

CREATE TABLE ACCOUNT(
	ACCOUNT_ID int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	USERNAME varchar(15) NOT NULL UNIQUE,
	PASSWORD varchar(255) NOT NULL,
	ROLE varchar(10) NOT NULL,
	ACTIVE bit NOT NULL DEFAULT 1
)
GO

CREATE TABLE TOKEN(
	TOKEN_ID int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TOKEN VARCHAR(255) NOT NULL,
	EXPIRY date NOT NULL,
	ACCOUNT_ID int NOT NULL,
	CONSTRAINT FK_TOKEN_USER
        FOREIGN KEY (ACCOUNT_ID)
        REFERENCES ACCOUNT(ACCOUNT_ID)
)
GO

CREATE TABLE LOAINHANVIEN(
	MALOAINV int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TEN nvarchar(100) NOT NULL
)
GO

CREATE TABLE NHANVIEN(
	MANV nchar(10) NOT NULL PRIMARY KEY,
	AVATAR varchar(255) NOT NULL,
	HO nvarchar(50) NOT NULL,
	TEN nvarchar(50) NOT NULL,
	PHAI bit NOT NULL DEFAULT 1,
	DIACHI nvarchar(100) NULL,
	SODIENTHOAI char(20) NULL,
	NGAYSINH date NULL,
	EMAIL varchar(50) NULL UNIQUE,
	MaLoaiNV int NOT NULL,
	DANGLAM bit NOT NULL DEFAULT 1,
	CONSTRAINT FK_NHANVIEN_LOAINHANVIEN
        FOREIGN KEY (MaLoaiNV)
        REFERENCES LOAINHANVIEN(MaLoaiNV)
)
GO

CREATE TABLE KHOA(
	MAKHOA nchar(10) NOT NULL PRIMARY KEY,
	TENKHOA nvarchar(50) NOT NULL
)
GO

CREATE TABLE LOP(
	MALOP nchar(10) NOT NULL PRIMARY KEY,
	TENLOP nvarchar(50) NOT NULL,
	KHOAHOC nchar(9) NOT NULL,
	MAKHOA nchar(10) NOT NULL,
	MANV nchar(10) NOT NULL,
	CONSTRAINT FK_LOP_KHOA 
		FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA),
	CONSTRAINT FK_LOP_NHANVIEN
        FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
)
GO

CREATE TABLE SINHVIEN(
	MASV nchar(10) NOT NULL PRIMARY KEY,
	AVATAR varchar(255) NOT NULL,
	HO nvarchar(50) NOT NULL,
	TEN nvarchar(50) NOT NULL,
	PHAI bit NOT NULL DEFAULT 1,
	DIACHI nvarchar(100) NULL,
	SODIENTHOAI char(20) NULL,
	NGAYSINH date NULL,
	EMAIL varchar(50) NULL UNIQUE,
	MALOP nchar(10) NOT NULL,
	DANGHOC bit NOT NULL DEFAULT 1,
	CONSTRAINT FK_SINHVIEN_LOP
		FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
)
GO

CREATE TABLE DONGHOCPHI(
	MASV nchar(10) NOT NULL,
	NIENKHOA nchar(9) NOT NULL,
	HOCKY int NOT NULL,
	HOCPHI int NOT NULL,
	CONSTRAINT PK_DONGHOCPHI PRIMARY KEY (MASV, NIENKHOA, HOCKY),
    CONSTRAINT FK_DONGHOCPHI_SINHVIEN 
		FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV)
)
GO

CREATE TABLE CT_DONGHOCPHI(
	MASV nchar(10) NOT NULL,
	NIENKHOA nchar(9) NOT NULL,
	HOCKY int NOT NULL,
	NGAYDONG date NOT NULL,
	SOTIENDONG int NOT NULL,
	CONSTRAINT PK_CTHOCPHI PRIMARY KEY (MASV, NIENKHOA, HOCKY, NGAYDONG),
	CONSTRAINT FK_CTDONGHOCPHI_HOCPHI
        FOREIGN KEY (MASV, NIENKHOA, HOCKY)
        REFERENCES DONGHOCPHI(MASV, NIENKHOA, HOCKY)
)
GO

CREATE TABLE GIANGVIEN(
	MAGV nchar(10) NOT NULL PRIMARY KEY,
	AVATAR varchar(255) NOT NULL,
	MAKHOA nchar(10) NOT NULL,
	HO nvarchar(50) NOT NULL,
	TEN nvarchar(50) NOT NULL,
	PHAI bit NOT NULL DEFAULT 1,
	DIACHI nvarchar(100) NULL,
	SODIENTHOAI char(20) NULL,
	NGAYSINH date NULL,
	EMAIL varchar(50) NULL UNIQUE,
	HOCVI nvarchar(20) NULL,
	HOCHAM nvarchar(20) NULL,
	CHUYENMON nvarchar(50) NULL,
	DANGDAY bit NOT NULL DEFAULT 1,
	CONSTRAINT FK_GIANGVIEN_KHOA
		FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
)
GO

CREATE TABLE MONHOC(
	MAMH nchar(10) NOT NULL PRIMARY KEY,
	TENMH nvarchar(50) NOT NULL,
	SOTIET_LT int NOT NULL,
	SOTIET_TH int NOT NULL,
	SOTINCHI int,
	MAKHOA nchar(10) NOT NULL,
	CONSTRAINT FK_MONHOC_KHOA
		FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
)
GO

CREATE TABLE LOPTINCHI(
	MALTC int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NIENKHOA nchar(9) NOT NULL,
	HOCKY int NOT NULL,
	MAMH nchar(10) NOT NULL,
	MAGV nchar(10) NOT NULL,
	SISO_TOIDA int NOT NULL,
	SISO_HIENTAI int NOT NULL,
	DAY_THUTRONGTUAN varchar(50) NULL,
	THOIGIAN_BATDAU date NULL,
	THOIGIAN_KETTHUC date NULL,
	HUYLOP bit NOT NULL DEFAULT 0,
	CONSTRAINT FK_LOPTINCHI_GIANGVIEN
        FOREIGN KEY (MAGV)
        REFERENCES GIANGVIEN(MAGV),
	CONSTRAINT FK_LOPTINCHI_MONHOC
        FOREIGN KEY (MAMH)
        REFERENCES MONHOC(MAMH)
)
GO

CREATE TABLE DANGKY(
	MALTC int NOT NULL,
	MASV nchar(10) NOT NULL,
	DIEM_CC int NULL,
	DIEM_GK float NULL,
	DIEM_CK float NULL,
	XEPLOAI varchar(20) NULL,
	HUYDANGKY bit NULL DEFAULT 0,
	CONSTRAINT PK_DANGKY PRIMARY KEY (MALTC, MASV),
	CONSTRAINT FK_DANGKY_SINHVIEN
        FOREIGN KEY (MASV)
        REFERENCES SINHVIEN(MASV),
	CONSTRAINT FK_DANGKY_LOPTINCHI
        FOREIGN KEY (MALTC)
        REFERENCES LOPTINCHI(MALTC)
)
GO
